### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by tcyrus**
- Updated `.gitignore`
- Removed `.DS_Store` and `.sass-cache`
- Created and added components to `bower.json`

### CODE REVIEW

**Comment by tcyrus** [comment]
@actionnick

**Comment by actionnick** [comment]
Thank you for the PR! I don't think we want to move from npm to bower. If you take out bower the PR is :+1:.

**Comment by tcyrus** [comment]
I assumed it was using bower since the repo already contained a directory named `components/bower_components`. Polymer cannot be installed through npm at this time, but I have modified the `package.json` so that npm can still be used for dependencies.

**Comment by actionnick** [comment]
You are absolutely right, I forgot about polymer not being available on npm and that's why we used bower.

**Pull request merged**
